version: '3'
services:
  download:
    build: download
    volumes:
    - "$PWD/data:/data"
    - "$PWD/download/:/app"
    command: "python /app/download.py"
  train:
    build: cnn
    volumes:
    - "$PWD/data:/data"
    - "$PWD/cnn/:/app"
    command: "python /app/train.py"